services:
  opensearch:
    build:
      context: ./opensearch
    environment:
      - cluster.name=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - node.name=opensearch
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9600:9600
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  dashboards:
    build:
      context: ./dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - LOGGING_JSON=false
