[workspace]
resolver = "3"
members = ["app/*", "lib/*"]

[workspace.dependencies]
core_ng = { path = "lib/core_ng" }

tracing = "*"
tracing-subscriber = "*"
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["rt"] }
tokio-stream = { version = "*" }
axum = { version = "*", features = ["macros"] }
axum-server = { version = "*", features = ["tls-rustls"] }
reqwest = { version = "*", default-features = false, features = [
    "stream",
    "rustls-tls",
] }

rdkafka = { version = "*", default-features = false, features = [
    "dynamic-linking",
    "libz",
    "tokio",
    "zstd",
] }

futures = "*"
bytes = "*"

uuid = { version = "*", features = ["v7"] }
chrono = { version = "*", features = ["serde"] }
base64 = "*"
