[workspace]
resolver = "3"
members = ["app/*", "lib/*"]

[workspace.dependencies]
core_ng = { path = "lib/core_ng" }

tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
anyhow = "*"

clap = { version = "*", features = ["derive"] }
clap_complete = "*"

serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["rt"] }
tokio-stream = { version = "*" }
axum = { version = "*", features = ["macros"] }
reqwest = { version = "*", features = ["stream"] }

futures = "*"
bytes = "*"

uuid = { version = "*", features = ["v7"] }
chrono = { version = "*", features = ["serde"] }
base64 = "*"
