name: Docker
on:
  push:
    tags: ["*.*.*"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: neowu
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: app/log_exporter/Dockerfile
          tags: "neowu/log-exporter:${{ env.TAG }}-rust"
          push: true
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: app/log_collector/Dockerfile
          tags: "neowu/log-collector:${{ env.TAG }}-rust"
          push: true
